<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Interview\AiOralExam.Modules.Interview\AiOralExam.Modules.Interview.csproj" />
    <ProjectReference Include="..\..\src\Modules\Reporting\AiOralExam.Modules.Reporting\AiOralExam.Modules.Reporting.csproj" />
  </ItemGroup>
</Project>
